### ISSUE TITLE
Feature Request: Ability to run entire file

### ISSUE THREAD

**Issue by al1-ce** [jellydn/quick-code-runner.nvim#33]
Can be actually done with simple
```lua
{
    "<leader>cr",
    "gg0vGg$:QuickCodeRunner<CR>",
    desc = "Quick File Code Runner",
    mode = "n",
},
```
As a keybind, but in relation to #32 would be nice to have custom command for running code without using template (because template would already be there)

**Comment by jellydn** [comment]
Thanks @al1-ce for suggestion. I would keep this simple so I've added your example as a tip.
